#!/usr/bin/env bash
# CRAFT V&V -- show what is in your course scratch directory, then clear it.
#
#   just clean-tmp          # list it, ask, then delete
#   just clean-tmp -y       # skip the question (for scripts)
#
# Scratch lives in ~/.vvtemp because /tmp is not writable for you on eustis.
# It holds mutated copies of DUTs, simulator logs, and formal work dirs -- all
# regenerated by re-running the step that made them. Nothing you wrote by hand
# is kept here, so clearing it never loses your work.
set -euo pipefail

GREEN='\033[0;32m'; YEL='\033[0;33m'; NC='\033[0m'

ROOT="${CRAFT_TMP:-$HOME/.vvtemp}"
YES=0
for a in "$@"; do case "$a" in -y|--yes) YES=1;; esac; done

if [ ! -d "$ROOT" ]; then
  printf "${GREEN}Nothing to clean${NC} -- %s does not exist yet.\n" "$ROOT"
  exit 0
fi

# Show what is about to go. du -sh per entry, oldest access first, so a student
# can see at a glance whether anything looks like it is still in use.
echo "Scratch directory: $ROOT"
echo
n=0
while IFS= read -r entry; do
  [ -e "$entry" ] || continue
  size=$(du -sh "$entry" 2>/dev/null | cut -f1)
  # GNU date takes -r <file>; BSD/macOS date takes -r <seconds>, so it errors
  # here and we fall through to stat. Students run this on their laptops too.
  when=$(date -r "$entry" '+%Y-%m-%d %H:%M' 2>/dev/null \
         || stat -f '%Sm' -t '%Y-%m-%d %H:%M' "$entry" 2>/dev/null \
         || echo '?')
  printf '  %-8s  %-16s  %s\n' "${size:-?}" "$when" "$(basename "$entry")"
  n=$((n+1))
done < <(find "$ROOT" -mindepth 1 -maxdepth 1 | sort)

if [ "$n" -eq 0 ]; then
  printf "\n${GREEN}Already empty.${NC} Nothing to delete.\n"
  exit 0
fi

total=$(du -sh "$ROOT" 2>/dev/null | cut -f1)
printf "\n%s item(s), %s total.\n" "$n" "${total:-?}"
printf "${YEL}Everything listed above will be deleted.${NC} It is all regenerated by re-running the step that made it.\n"

if [ "$YES" -ne 1 ]; then
  # Read from the terminal, not stdin, so this still asks when piped.
  printf "Delete it? [y/N] "
  read -r reply < /dev/tty || reply=""
  case "$reply" in
    y|Y|yes|YES) ;;
    *) echo "Left alone. Nothing was deleted."; exit 0;;
  esac
fi

find "$ROOT" -mindepth 1 -maxdepth 1 -exec rm -rf {} +
printf "${GREEN}Cleared${NC} %s\n" "$ROOT"
